[package]
name = "simple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpc-discord = { path = "../../" }
dotenv = "0.15.0"
tokio = { version = "1.24.2", features = ["full"] }
